# vim: set ft=ansible:
---
# assumes flatpak already installed (on Fedora it is)
- name: Flatpak
  hosts: localhost
  tags:
    - flatpak
  tasks:
    - name: Add flatpak repo
      command: 'flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo' 

- name: Browser and base
  hosts: localhost
  collections:
    - community.general
  gather_facts: false
  tags:
    - browser_and_base
  tasks:
  - name: Set up Visual Studio Code repository
    yum_repository:
      name: code
      description: Visual Studio Code
      baseurl: "https://packages.microsoft.com/yumrepos/vscode"
      enabled: yes
      gpgcheck: yes
      gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"

  - name: Install packages
    dnf:
      name:
        - "google-chrome-stable"
        - "htop"
        - "gnome-tweak-tool"
        - "workrave"
        - "workrave-gtk2"
        - "gparted"
        - "tmux"
        - "powerline"
        - "powerline-fonts"
        - "tmux-powerline"
        - "vim-powerline"
        - "vim-enhanced"
        - "vim-X11"
        - "code"
        #- "chrome-gnome-shell"
      state: present

  - name: Install flatpaks
    community.general.flatpak:
      name: "{{ item }}"
      state: present
    with_items:
      - "org.filezillaproject.Filezilla"
      - "com.github.bcedu.vgrive"
      - "org.mozilla.Thunderbird"
      - "com.getpostman.Postman"
      - "org.gnome.DejaDup"

  - name: inotify watches for various reasons
    lineinfile:
      dest: /etc/sysctl.conf
      line: "fs.inotify.max_user_watches = 1000000"
      state: present
      insertafter: EOF
  - name: persist inotify changes
    command: "sysctl -p"

- name: Communication
  hosts: localhost
  gather_facts: false
  tags:
    - communication_tools
  tasks:
  - name: Install flatpaks
    flatpak:
      name: "{{ item }}"
      state: present
    with_items:
      - "com.skype.Client"
      - "com.slack.Slack"
      - "com.discordapp.Discord"

- name: Media
  hosts: localhost
  gather_facts: false
  tags:
    - media
  tasks:
  - name: Install packages
    dnf:
      name: 
        - "gstreamer1-plugins-bad-free"
        - "gstreamer1-plugins-bad-free-extras"
        - "gstreamer1-plugins-good"
        - "gstreamer1-plugins-good-extras"
        - "gstreamer1-plugins-ugly-free"
        - "gstreamer1-libav"
        - "mediainfo"
      state: present
  - name: Install flatpaks
    flatpak:
      name: "{{ item }}"
      state: present
    with_items:
      - "org.videolan.VLC"
      - "com.spotify.Client"
      - "org.audacityteam.Audacity"

- name: Graphic design, photo editing, video
  hosts: localhost
  gather_facts: false
  tags:
    - graphic_design_and_photo_editing
  tasks:
  - name: Install packages
    dnf:
      name:
        - "LibRaw"
        - "python3-click"
        - "perl-Image-ExifTool"
        - "ImageMagick"
      state: present
  - name: Install flatpaks
    flatpak:
      name: "{{ item }}"
      state: present
    with_items:
      - "org.gimp.GIMP"
      - "org.darktable.Darktable"
      - "org.blender.Blender"
      - "org.geeqie.Geeqie"

- name: Java and WebEx support
  hosts: localhost
  gather_facts: false
  tags:
    - java_and_webex_support
  tasks:
  - name: Install packages
    dnf:
      name:
        - "java"
      state: present
